### ISSUE TITLE
how to train the model on multiple GPUs?

### ISSUE THREAD

**Issue by anchoret2009** [dome272/Diffusion-Models-pytorch#35]
thanks.

**Comment by NoahSchiro** [comment]
Hi I am not the project maintainer but this question is more oriented towards a question about how PyTorch works. PyTorch has great documentation on multi-gpu training which you can find here https://pytorch.org/tutorials/beginner/ddp_series_intro.html

You will need to modify some of the variables in the train() function to do match the above documentation. It believe it is fairly straightforward as long as you are familiar with pytorch

**Comment by anchoret2009** [comment]
thanks~
