### ISSUE TITLE
qn regarding DoubleConv

### ISSUE THREAD

**Issue by Qbiwan** [dome272/Diffusion-Models-pytorch#5]
Any reason why there is no gelu in the else clause (when there is no self.residual)? a bit puzzled.

```
class DoubleConv(nn.Module):

    def forward(self, x):
        if self.residual:
            return F.gelu(x + self.double_conv(x))
        else:
            return self.double_conv(x)
```

**Comment by dome272** [comment]
You are right, you could just add. I didnt experience any problems during training and just went with this architecture. Feel free to try it out if it changes something :)

**Comment by Qbiwan** [comment]
Cool! 
Btw, love your youtubes, watched them quite a few times  :thumbsup: :thumbsup: :thumbsup:

**Comment by AdamWojtczak** [comment]
Hi @Qbiwan,
So would this code look like this after adding GELU?

`class DoubleConv(nn.Module):

    def forward(self, x):
        if self.residual:
            return F.gelu(x + self.double_conv(x))
        else:
            return  F.gelu(self.double_conv(x))`
